# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: acorbeau <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/04/11 17:02:02 by acorbeau          #+#    #+#              #
#    Updated: 2017/04/26 12:41:09 by acorbeau         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

FLAGS = -c -Wall -Werror -Wextra

SRCS = ft_atoi.c \
		ft_nlen.c \
		ft_bzero.c \
		ft_isalpha.c \
		ft_isblank.c \
		ft_ispunct.c \
		ft_isascii.c \
		ft_lstrev.c \
		ft_strsub.c \
		ft_isdigit.c \
		ft_isprint.c \
		ft_isspace.c \
		ft_isalnum.c \
		ft_memcmp.c \
		ft_memchr.c \
		ft_memcpy.c \
		ft_memmove.c \
		ft_memset.c \
		ft_strcat.c \
		ft_strchr.c \
		ft_strcmp.c \
		ft_strcpy.c \
		ft_strdup.c \
		ft_strlcat.c \
		ft_strlen.c \
		ft_strncat.c \
		ft_strncmp.c \
		ft_strncpy.c \
		ft_strrchr.c \
		ft_tolower.c \
		ft_toupper.c \
		ft_itoa.c \
		ft_putstr.c \
		ft_putchar.c \
		ft_putnbr.c \
		ft_perror.c \
		ft_islower.c \
		ft_isupper.c \
		ft_memccpy.c \
		ft_strnstr.c \
		ft_strstr.c \
		ft_strnew.c \
		ft_strnequ.c \
		ft_strequ.c \
		ft_strmap.c \
		ft_strmapi.c \
		ft_striter.c \
		ft_striteri.c \
		ft_strclr.c \
		ft_strdel.c \
		ft_memdel.c \
		ft_memalloc.c \
		ft_putendl_fd.c \
		ft_putendl.c \
		ft_putnbr_fd.c \
		ft_putchar_fd.c \
		ft_putstr_fd.c \
		ft_segcount.c \
		ft_strjoin.c \
		ft_strtrim.c \
		ft_seglen.c \
		ft_strsplit.c \
		ft_lstadd.c \
		ft_lstdel.c \
		ft_lstdelone.c \
		ft_lstiter.c \
		ft_lstmap.c \
		ft_lstnew.c \
		ft_max.c \
		ft_lstpop.c \
		ft_lstcreate.c \
		ft_lstswap.c \
		ft_lstsort.c \
		get_next_line.c \
		ft_memdup.c \
		ft_lstaddfront.c

OBJS = $(SRCS:.c=.o)

$(NAME): $(OBJS)
	ar rc $(NAME) $(OBJS)
	ranlib $(NAME)

all: $(NAME)

%.o: %.c
	clang $(FLAGS) -o $@ $< -I ../includes/

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all
